### ISSUE TITLE
quickcheck_macros: expected struct `syntax::codemap::Spanned`, found enum `syntax::ast::Constness`

### ISSUE THREAD

**Issue by alopatindev** [BurntSushi/quickcheck#140]
quickcheck_macros fails to build with recent rust 1.13.0-nightly (497d67d70 2016-09-01)

```
error[E0308]error[E0308]: mismatched types
   --> src/lib.rs:121:38
    |
121 |         decl, ast::Unsafety::Normal, ast::Constness::NotConst, Abi::Rust,
    |                                      ^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `syntax::codemap::Spanned`, found enum `syntax::ast::Constness`
: mismatched types
   --> src/lib.rs:121:38
    |
121 |         decl, ast::Unsafety::Normal, ast::Constness::NotConst, Abi::Rust,
    |                                      ^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `syntax::codemap::Spanned`, found enum `syntax::ast::Constness`
    |
    |
    = note: expected type `syntax::codemap::Spanned<syntax::ast::Constness>`    = note: expected type `syntax::codemap::Spanned<syntax::ast::Constness>`

    = note:    found type `syntax::ast::Constness`    = note:    found type `syntax::ast::Constness`
```

Full [`cargo build --verbose` log](https://gist.github.com/alopatindev/54ce3722cbd6907939a4f34b9547b77c)

**Comment by BurntSushi** [comment]
This should be fixed and is on crates.io in `quickcheck_macros 0.2.29`.
